version: "2"

services:
  aosp:
    image: aosp:4.x
    command:  cd /usr/local/aosp && source build/envsetup.sh && ping 127.0.0.1
    container_name: aosp-4.x
    volumes:
        - ~/aosp/ccache:/tmp/ccache
        - /usr/local/aosp:/usr/local/aosp
        - ~/.gitconfig:/root/.gitconfig