version: "2"

services:
  aosp:
    image: aosp:6.x
    command: ping 127.0.0.1
    container_name: aosp-6.x
    volumes:
        - ~/aosp/ccache:/tmp/ccache
        - /usr/local/aosp-6.x:/usr/local/aosp
        - ~/.gitconfig:/root/.gitconfig