version: "2"

services:
  aosp:
    image: aosp:7.x
    command: ping 127.0.0.1
    container_name: aosp-7.x
    volumes:
        - ~/aosp/ccache:/tmp/ccache
        - /usr/local/aosp-7.x:/usr/local/aosp
        - ~/.gitconfig:/root/.gitconfig