version: "2"

services:
  aosp:
    image: aosp:5.x
    command: ping 127.0.0.1
    container_name: cm-12.1
    volumes:
        - ~/aosp/ccache:/tmp/ccache
        - /usr/local/aosp-5.x:/usr/local/aosp
        - ~/.gitconfig:/root/.gitconfig
